CREATE TABLE UNIDADE_EDUCACIONAL(
   ID_UNIDADE_EDUCACIONAL INT PRIMARY KEY     NOT NULL,
   DS_UNIDADE_EDUCACIONAL TEXT    NOT NULL,
   DATA_INAUGURACAO       DATE     NOT NULL
);

drop table TABLE DIARIO_CLASSE;
CREATE TABLE DIARIO_CLASSE
(
   ID_DIARIO_CLASSE serial PRIMARY KEY     NOT NULL,
   ID_DISCIPLINA INT NOT NULL,
   ID_ALUNO INT NOT NULL,
   DATA_DIARIO  DATE     NOT NULL,
   PRESENCA_AULA CHAR(1)    NOT NULL
);

alter table DIARIO_CLASSE 
    add constraint fk_DIARIO_CLASSE_discipl
    foreign key (ID_DISCIPLINA) 
    REFERENCES DISCIPLINA (ID_DISCIPLINA);

drop TABLE DISCIPLINA;
CREATE TABLE DISCIPLINA
(
   ID_DISCIPLINA serial PRIMARY KEY     NOT NULL,
   CD_DISCIPLINA TEXT    NOT NULL,
   DS_DISCIPLINA TEXT    NOT NULL,
   DS_PROFESSOR TEXT    NOT NULL,
   ID_PROFESSOR int    NOT NULL,
   PERIODO TEXT    NOT NULL,
   ID_TURMA INT NOT NULL,
   DS_TURMA TEXT NOT NULL
);

alter table DISCIPLINA 
    add constraint fk_DISCIPLINA_PROF
    foreign key (ID_PROFESSOR) 
    REFERENCES PROFESSOR (ID_PROFESSOR);

drop  TABLE RL_DISCIPL_ALUNO;
CREATE TABLE RL_DISCIPL_ALUNO
(
   ID_RL_DISCIPL_ALUNO serial PRIMARY KEY     NOT NULL,
   ID_DISCIPLINA INT 	NOT NULL,
   ID_ALUNO INT NOT NULL
);

alter table RL_DISCIPL_ALUNO 
    add constraint fk_RL_DISCIPL_ALUNO_DISCIP
    foreign key (ID_DISCIPLINA) 
    REFERENCES DISCIPLINA (ID_DISCIPLINA);

alter table RL_DISCIPL_ALUNO 
    add constraint fk_RL_DISCIPL_ALUNO
    foreign key (ID_ALUNO) 
    REFERENCES ALUNO (ID_ALUNO);

ALTER TABLE RL_DISCIPL_ALUNO ADD CONSTRAINT RL_DISCIPL_ALUNO_UQ UNIQUE (ID_DISCIPLINA, ID_ALUNO);

drop table aluno;
CREATE TABLE ALUNO
(
   ID_ALUNO serial PRIMARY KEY     NOT NULL,
   DS_ALUNO TEXT    NOT NULL,
   DATA_NASCIMENTO  DATE     NOT NULL,
   CONTATO1 CHAR(50) NULL,
   CONTATO2 CHAR(50) NULL,
   EMAIL CHAR(50) NULL
);

CREATE INDEX ALUNO_DS_IX ON ALUNO (ID_ALUNO);

drop TABLE RESPONSAVEL_ALUNO;
CREATE TABLE RESPONSAVEL_ALUNO
(
   ID_RESPONSAVEL_ALUNO serial PRIMARY KEY     NOT NULL,
   DS_RESPONSAVEL_ALUNO TEXT    NOT NULL,
   DATA_NASCIMENTO  DATE     NOT NULL,
   CONTATO1 CHAR(50) NULL,
   CONTATO2 CHAR(50) NULL,
   EMAIL CHAR(50) NULL,
   LOGIN CHAR(50) NULL,
   PASSW CHAR(50) NULL
);

drop table RL_RESPONSAVEL_ALUNO;
CREATE TABLE RL_RESPONSAVEL_ALUNO
(
	ID_RL_RESPONSAVEL_ALUNO serial PRIMARY KEY     NOT NULL,
	ID_RESPONSAVEL_ALUNO INT NOT NULL,
	ID_ALUNO INT NOT NULL
);


alter table RL_RESPONSAVEL_ALUNO 
    add constraint fk_RL_RESPONS_ALUNO
    foreign key (ID_ALUNO) 
    REFERENCES ALUNO (ID_ALUNO);

alter table RL_RESPONSAVEL_ALUNO
    add constraint fk_RL_RESPONS_RESPONS
    foreign key (ID_RESPONSAVEL_ALUNO) 
    REFERENCES RESPONSAVEL_ALUNO (ID_RESPONSAVEL_ALUNO);

drop TABLE PROFESSOR;
CREATE TABLE PROFESSOR
(
   ID_PROFESSOR serial PRIMARY KEY     NOT NULL,
   DS_PROFESSOR TEXT    NOT NULL,
   CPF CHAR(14)    NOT NULL,
   DATA_NASCIMENTO  DATE     NOT NULL,
   CONTATO1 CHAR(50) NULL,
   CONTATO2 CHAR(50) NULL,
   EMAIL CHAR(50) NULL,
   LOGIN CHAR(50) NULL,
   PASSW CHAR(50) NULL
);

ALTER TABLE PROFESSOR ADD CONSTRAINT PROFESSOR_CPF_UQ UNIQUE (CPF);